apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: pet-clinic-app
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: mysql-secretstore
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
  - secretKey: mysql-url
    remoteRef:
        key: dev/nexus-login
        property: url
  - secretKey: mysql-username
    remoteRef:
        key: dev/nexus-login
        property: username
  - secretKey: mysql-password
    remoteRef:
      key: dev/nexus-login
      property: password