apiVersion: v1
kind: Deployment
metadata:
  name: hello-world
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
